/**
 * The stable, machine-readable error catalogue.
 *
 * Every code here is:
 *   • the key the UI branches on (NEVER branch on a message string),
 *   • the i18n message key in core/i18n/messages/{en,am}.json,
 *   • part of the API contract once M22 (Phase 2) consumes it.
 *
 * Codes are therefore append-only in spirit: renaming one is a breaking change.
 */

export const ERROR_CODES = {
  // ── Generic / infrastructure ───────────────────────────────────────────────
  INTERNAL: 'INTERNAL',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  MAIL_UNAVAILABLE: 'MAIL_UNAVAILABLE',
  SCANNER_UNAVAILABLE: 'SCANNER_UNAVAILABLE',

  // ── Request / validation ───────────────────────────────────────────────────
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // ── Authentication / authorization ─────────────────────────────────────────
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_POLICY_VIOLATION: 'PASSWORD_POLICY_VIOLATION',
  PASSWORD_RECENTLY_USED: 'PASSWORD_RECENTLY_USED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',

  // ── Resource ───────────────────────────────────────────────────────────────
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  /** Optimistic lock lost — someone else changed the record. */
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',

  // ── Lifecycle (consignment / lot / job) ────────────────────────────────────
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  ENTITY_NOT_IN_EXPECTED_STATE: 'ENTITY_NOT_IN_EXPECTED_STATE',

  // ── Master data (M02) ──────────────────────────────────────────────────────
  MASTER_DATA_CODE_IMMUTABLE: 'MASTER_DATA_CODE_IMMUTABLE',
  MASTER_DATA_IN_USE: 'MASTER_DATA_IN_USE',
  EFFECTIVE_PERIOD_OVERLAP: 'EFFECTIVE_PERIOD_OVERLAP',
  NO_EFFECTIVE_VERSION: 'NO_EFFECTIVE_VERSION',

  // ── Customer / onboarding (M08) ────────────────────────────────────────────
  APPLICATION_NOT_REVIEWABLE: 'APPLICATION_NOT_REVIEWABLE',
  MANDATORY_DOCUMENT_MISSING: 'MANDATORY_DOCUMENT_MISSING',
  MANDATORY_DOCUMENT_UNVERIFIED: 'MANDATORY_DOCUMENT_UNVERIFIED',
  DOCUMENT_EXPIRED: 'DOCUMENT_EXPIRED',
  REJECTION_COMMENT_REQUIRED: 'REJECTION_COMMENT_REQUIRED',
  CUSTOMER_ON_HOLD: 'CUSTOMER_ON_HOLD',

  // ── Files ──────────────────────────────────────────────────────────────────
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_CONTENT_MISMATCH: 'FILE_CONTENT_MISMATCH',
  FILE_NOT_SCANNED: 'FILE_NOT_SCANNED',
  FILE_INFECTED: 'FILE_INFECTED',

  // ── Warehouse / capacity (M12) ─────────────────────────────────────────────
  INSUFFICIENT_CAPACITY: 'INSUFFICIENT_CAPACITY',
  LOCATION_INACTIVE: 'LOCATION_INACTIVE',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  RESERVATION_ALREADY_CONSUMED: 'RESERVATION_ALREADY_CONSUMED',
  SAFE_FILL_EXCEEDED: 'SAFE_FILL_EXCEEDED',

  // ── Stock ledger ───────────────────────────────────────────────────────────
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  NEGATIVE_BALANCE: 'NEGATIVE_BALANCE',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  ADJUSTMENT_REASON_REQUIRED: 'ADJUSTMENT_REASON_REQUIRED',
  LEDGER_IMBALANCE: 'LEDGER_IMBALANCE',

  // ── Inbound (M11) ──────────────────────────────────────────────────────────
  DELIVERY_REQUEST_NOT_APPROVED: 'DELIVERY_REQUEST_NOT_APPROVED',
  CAPACITY_CHECK_REQUIRED: 'CAPACITY_CHECK_REQUIRED',
  KESHA_COUNT_ALREADY_CONFIRMED: 'KESHA_COUNT_ALREADY_CONFIRMED',
  WITNESS_REQUIRED: 'WITNESS_REQUIRED',
  WITNESS_MUST_DIFFER: 'WITNESS_MUST_DIFFER',

  // ── Scheduling (M14) ───────────────────────────────────────────────────────
  LOT_NOT_IN_STORE: 'LOT_NOT_IN_STORE',
  LOT_ALREADY_COMMITTED: 'LOT_ALREADY_COMMITTED',
  APPOINTMENT_OVERLAP: 'APPOINTMENT_OVERLAP',
  APPOINTMENT_IN_PAST: 'APPOINTMENT_IN_PAST',
  DELAY_REASON_REQUIRED: 'DELAY_REASON_REQUIRED',
  LINE_UNAVAILABLE: 'LINE_UNAVAILABLE',

  // ── Processing (M15) ───────────────────────────────────────────────────────
  JOB_NOT_STARTED: 'JOB_NOT_STARTED',
  JOB_ALREADY_STARTED: 'JOB_ALREADY_STARTED',
  JOB_STARTED_BEFORE_WINDOW: 'JOB_STARTED_BEFORE_WINDOW',
  MASS_BALANCE_OUT_OF_TOLERANCE: 'MASS_BALANCE_OUT_OF_TOLERANCE',
  VARIANCE_EXPLANATION_REQUIRED: 'VARIANCE_EXPLANATION_REQUIRED',
  OUTPUT_ALREADY_RECORDED: 'OUTPUT_ALREADY_RECORDED',
  NO_OUTPUTS_RECORDED: 'NO_OUTPUTS_RECORDED',

  // ── Acceptance (M16) ───────────────────────────────────────────────────────
  ACCEPTANCE_ALREADY_SIGNED: 'ACCEPTANCE_ALREADY_SIGNED',
  ACCEPTANCE_NOT_ISSUED: 'ACCEPTANCE_NOT_ISSUED',

  // ── Dispatch (M17) ─────────────────────────────────────────────────────────
  NOT_ACCEPTED_BY_CUSTOMER: 'NOT_ACCEPTED_BY_CUSTOMER',
  GATE_PASS_ALREADY_USED: 'GATE_PASS_ALREADY_USED',
  GATE_PASS_EXPIRED: 'GATE_PASS_EXPIRED',
  GATE_PASS_VEHICLE_MISMATCH: 'GATE_PASS_VEHICLE_MISMATCH',
  CLEARANCE_FAILED: 'CLEARANCE_FAILED',

  // ── Kesha (M13) ────────────────────────────────────────────────────────────
  BAG_RECONCILIATION_IMBALANCE: 'BAG_RECONCILIATION_IMBALANCE',
  INSUFFICIENT_EMPTY_BAGS: 'INSUFFICIENT_EMPTY_BAGS',

  // ── Labour (M18) ───────────────────────────────────────────────────────────
  LABOUR_QUANTITY_NOT_DERIVED: 'LABOUR_QUANTITY_NOT_DERIVED',
  NO_APPLICABLE_PIECE_RATE: 'NO_APPLICABLE_PIECE_RATE',
  GANG_HAS_NO_MEMBERS: 'GANG_HAS_NO_MEMBERS',
  VOUCHER_ALREADY_ISSUED: 'VOUCHER_ALREADY_ISSUED',

  // ── Printing / numbering (M06) ─────────────────────────────────────────────
  NUMBER_SERIES_NOT_FOUND: 'NUMBER_SERIES_NOT_FOUND',
  NUMBER_SERIES_INACTIVE: 'NUMBER_SERIES_INACTIVE',
  DOCUMENT_TEMPLATE_NOT_FOUND: 'DOCUMENT_TEMPLATE_NOT_FOUND',
  QR_TOKEN_INVALID: 'QR_TOKEN_INVALID',
  QR_TOKEN_REVOKED: 'QR_TOKEN_REVOKED',

  // ── Notification (M04) ─────────────────────────────────────────────────────
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  NOTIFICATION_RECIPIENT_MISSING: 'NOTIFICATION_RECIPIENT_MISSING',

  // ── Administration (M23) ───────────────────────────────────────────────────
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  SETTING_VALUE_INVALID: 'SETTING_VALUE_INVALID',
  SETTING_NOT_EDITABLE: 'SETTING_NOT_EDITABLE',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/** Every code, for exhaustiveness checks and i18n coverage tests. */
export const ALL_ERROR_CODES = Object.values(ERROR_CODES) as readonly ErrorCode[]
