import {
  timestamp,
  uuid,
  integer,
  numeric,
  text,
  boolean,
  date,
  char,
} from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

/**
 * Reusable column builders. EVERY table uses these; nothing declares a raw numeric column.
 *
 * The critical property is `mode: 'string'` on numeric columns: the driver returns Postgres
 * `numeric` as a string and it must stay a string until a Weight/Money value object parses
 * it. A JS `number` in between silently loses precision, and a precision loss in a weight is
 * a commercial dispute.
 *
 * docs/architecture/04-database-and-migrations.md §4.1
 */

/** Primary key. Values are generated by the application (UUIDv7, time-ordered). */
export const id = () => uuid('id').primaryKey()

/** Foreign-key column, named `<table>_id` by convention. */
export const fk = (name: string) => uuid(name)

/** Weight in kilograms — numeric(14,3), exact to the gram. NEVER float. */
export const weightKg = (name: string) =>
  numeric(name, { precision: 14, scale: 3, mode: 'string' })

/** A count of kesha (bags) — always a whole number. */
export const keshaCount = (name: string) => integer(name)

/** Money amount — numeric(14,2). Always paired with a currency column. */
export const moneyAmount = (name: string) =>
  numeric(name, { precision: 14, scale: 2, mode: 'string' })

/** ISO 4217 currency code. */
export const currency = (name = 'currency') => char(name, { length: 3 }).default('ETB')

/** Percentage — numeric(6,3), e.g. yield and mass-balance variance. */
export const percent = (name: string) =>
  numeric(name, { precision: 6, scale: 3, mode: 'string' })

/** An instant. ALWAYS `timestamptz`; business dates are derived in core/utils/date.ts. */
export const instant = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' })

/** A calendar date with no time component, named `<x>_on` by convention. */
export const calendarDate = (name: string) => date(name, { mode: 'string' })

/**
 * A stable business code on a lookup table. Immutable once referenced — application code
 * keys behaviour on this, never on a UUID or a display name.
 */
export const code = (name = 'code') => text(name).notNull()

/** Bilingual display names — every lookup table carries both (M02). */
export const displayNames = () => ({
  nameEn: text('name_en').notNull(),
  nameAm: text('name_am'),
})

/**
 * Columns every business table carries.
 * `version` drives optimistic concurrency: UPDATE ... WHERE id = $1 AND version = $2,
 * zero rows affected → ConcurrencyError → "someone else changed this".
 */
export const auditColumns = () => ({
  createdAt: instant('created_at')
    .notNull()
    .default(sql`now()`),
  createdBy: uuid('created_by').notNull(),
  updatedAt: instant('updated_at')
    .notNull()
    .default(sql`now()`),
  updatedBy: uuid('updated_by'),
  version: integer('version').notNull().default(0),
})

/**
 * Columns for APPEND-ONLY tables (stock_movement, domain_event, audit_log, notification,
 * printed_document, *_status_history, gate_event).
 *
 * Deliberately omits updated_* and version: these rows cannot be updated, and having the
 * columns invites someone to try.
 */
export const appendOnlyColumns = () => ({
  createdAt: instant('created_at')
    .notNull()
    .default(sql`now()`),
  createdBy: uuid('created_by'),
})

/**
 * The two timestamps every operational record needs.
 *
 * Coffee arrives at 17:40 and is entered at 09:10 the next morning. With only one timestamp,
 * dwell time, daily throughput and delay analysis are all quietly wrong — and a growing gap
 * between them is itself an operational signal.
 */
export const occurrenceColumns = () => ({
  occurredAt: instant('occurred_at').notNull(),
  recordedAt: instant('recorded_at')
    .notNull()
    .default(sql`now()`),
})

/** Soft-activation. We deactivate rather than delete, so history stays explicable. */
export const activeFlag = () => boolean('is_active').notNull().default(true)

/** Effective-dated versioning (M02 key control). Paired with an EXCLUDE constraint in SQL. */
export const effectivePeriod = () => ({
  effectiveFrom: calendarDate('effective_from').notNull(),
  effectiveTo: calendarDate('effective_to'),
})

/** Groups every event and movement of one business operation. */
export const correlationColumns = () => ({
  correlationId: uuid('correlation_id').notNull(),
  causationId: uuid('causation_id'),
})

/** Polymorphic reference to the document that caused a record. */
export const sourceReference = () => ({
  sourceType: text('source_type').notNull(),
  sourceId: uuid('source_id').notNull(),
})
